spring.application.name=global-class-booking-system

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/yugabyte}
spring.datasource.username=${DB_USERNAME:yugabyte}
spring.datasource.password=${DB_PASSWORD:yugabyte}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.separator=@@
spring.sql.init.continue-on-error=true

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=false

server.error.include-message=never
